meta_name: "Quandary"
meta_title: "Quandary - Games of absurd dilemmas"
meta_description: "Young adults looking for a humorous and light-hearted experience"
meta_image: "https://res.cloudinary.com/drfmymoki/image/upload/v1678621465/Quandary%20Avatars/Q_Logo_Shadow_o6wurs.svg"
